

name: My Workflow

on:
  workflow_dispatch:
    
jobs:
  prepare:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        shell: python
    steps:
      - name: python runner
        run: | 
            variable = 'world'
            print(f'hello {variable}')
